In [ ]:
import pandas as pd
import numpy as np
from google.colab import files

In [ ]:
upload = files.upload()

Saving car data.csv to car data.csv

In [ ]:
df = pd.read_csv('car data.csv')

In [ ]:
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [ ]:
# Values count

marks = pd.DataFrame([
    [100,200,10],
    [200,230,12],
    [200,11,13],
    [300,123,21]
],columns = ['Physics','Chemistry','Maths']
)

In [ ]:
marks

   Physics  Chemistry  Maths
0      100        200     10
1      200        230     12
2      200         11     13
3      300        123     21

In [ ]:
a = pd.Series([1,2,3,4,5])

In [ ]:
a.value_counts()

1    1
2    1
3    1
4    1
5    1
Name: count, dtype: int64

In [ ]:
marks.value_counts()

Physics  Chemistry  Maths
100      200        10       1
200      11         13       1
         230        12       1
300      123        21       1
Name: count, dtype: int64

In [ ]:
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [ ]:
car_name = df['Car_Name']

In [ ]:
car_drive = df['Kms_Driven']

In [ ]:
# Sort Value

In [ ]:
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
a.sort_values()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
df.sort_values('Year')

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
39,sx4,2003,2.25,7.98,62000,Petrol,Dealer,Manual,0
37,800,2003,0.35,2.28,127000,Petrol,Individual,Manual,0
77,corolla,2004,1.50,12.35,135154,Petrol,Dealer,Automatic,0
54,innova,2005,2.75,10.21,90000,Petrol,Individual,Manual,0
189,Hero Super Splendor,2005,0.20,0.57,55000,Petrol,Individual,Manual,0
...,...,...,...,...,...,...,...,...,...
27,swift,2017,6.00,6.49,16200,Petrol,Individual,Manual,0
268,brio,2017,4.80,5.80,19000,Petrol,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
5,vitara brezza,2018,9.25,9.83,2071,Diesel,Dealer,Manual,0

In [ ]:
# By default if we do sort on missing col then it keep in last

In [ ]:
# Rank(Series)

k = df['Kms_Driven']

In [ ]:
k

0      27000
1      43000
2       6900
3       5200
4      42450
       ...
296    33988
297    60000
298    87934
299     9000
300     5464
Name: Kms_Driven, Length: 301, dtype: int64

In [ ]:
k.rank()

0      133.5
1      203.5
2       36.5
3       25.0
4      201.0
       ...
296    158.0
297    260.5
298    288.0
299     45.0
300     27.0
Name: Kms_Driven, Length: 301, dtype: float64

In [ ]:
df['Kms_Driven'].rank(ascending=False)

0      168.5
1       98.5
2      265.5
3      277.0
4      101.0
       ...
296    144.0
297     41.5
298     14.0
299    257.0
300    275.0
Name: Kms_Driven, Length: 301, dtype: float64

In [ ]:
marks.sort_index()

   Physics  Chemistry  Maths
0      100        200     10
1      200        230     12
2      200         11     13
3      300        123     21

In [ ]:
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [ ]:
df.sort_index(ascending=False)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0

In [ ]:
# Set Index ( DataFrame) --> Inplace
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [ ]:
df.set_index('Car_Name')

,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
Car_Name,,,,,,,,
ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...
city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [ ]:
# Reset Index -> Just reverse of set index ( It back to default index )

In [ ]:
df.reset_index()

,index,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...,...
296,296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [ ]:
# Rename (Dataframe) -> Index

df.set_index('Year',inplace=True)

In [ ]:
df

,Car_Name,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
Year,,,,,,,,
2014,ritz,3.35,5.59,27000,Petrol,Dealer,Manual,0
2013,sx4,4.75,9.54,43000,Diesel,Dealer,Manual,0
2017,ciaz,7.25,9.85,6900,Petrol,Dealer,Manual,0
2011,wagon r,2.85,4.15,5200,Petrol,Dealer,Manual,0
2014,swift,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...
2016,city,9.50,11.60,33988,Diesel,Dealer,Manual,0
2015,brio,4.00,5.90,60000,Petrol,Dealer,Manual,0
2009,city,3.35,11.00,87934,Petrol,Dealer,Manual,0
2017,city,11.50,12.50,9000,Diesel,Dealer,Manual,0
2016,brio,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [ ]:
df.rename(columns={'Car_Name':'Name' ,'Kms_Driven':'Kms'},inplace = True)

In [ ]:
df

,Name,Selling_Price,Present_Price,Kms,Fuel_Type,Seller_Type,Transmission,Owner
Year,,,,,,,,
2014,ritz,3.35,5.59,27000,Petrol,Dealer,Manual,0
2013,sx4,4.75,9.54,43000,Diesel,Dealer,Manual,0
2017,ciaz,7.25,9.85,6900,Petrol,Dealer,Manual,0
2011,wagon r,2.85,4.15,5200,Petrol,Dealer,Manual,0
2014,swift,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...
2016,city,9.50,11.60,33988,Diesel,Dealer,Manual,0
2015,brio,4.00,5.90,60000,Petrol,Dealer,Manual,0
2009,city,3.35,11.00,87934,Petrol,Dealer,Manual,0
2017,city,11.50,12.50,9000,Diesel,Dealer,Manual,0
2016,brio,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [ ]:
# Unique (Series)

a.unique()

array([1, 2, 3, 4, 5])

In [ ]:
df['Fuel_Type'].unique()

array(['Petrol', 'Diesel', 'CNG'], dtype=object)

In [ ]:
# isnull(Series + DataFrame)

df['Owner'].isnull().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

Name             0
Selling_Price    0
Present_Price    0
Kms              0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [ ]:
# notnull ( Series + DataFrame)

df['Owner'].notnull().sum()

np.int64(301)

In [ ]:
df.notnull().sum()

Name             301
Selling_Price    301
Present_Price    301
Kms              301
Fuel_Type        301
Seller_Type      301
Transmission     301
Owner            301
dtype: int64

In [ ]:
# Has nan ( Series + DataFrame )   -> Check is there any missing value

df['Owner'].hasnans

False

In [ ]:
df['Kms'].dropna()

Year
2014    27000
2013    43000
2017     6900
2011     5200
2014    42450
        ...
2016    33988
2015    60000
2009    87934
2017     9000
2016     5464
Name: Kms, Length: 301, dtype: int64

In [ ]:
df.dropna()

,Name,Selling_Price,Present_Price,Kms,Fuel_Type,Seller_Type,Transmission,Owner
Year,,,,,,,,
2014,ritz,3.35,5.59,27000,Petrol,Dealer,Manual,0
2013,sx4,4.75,9.54,43000,Diesel,Dealer,Manual,0
2017,ciaz,7.25,9.85,6900,Petrol,Dealer,Manual,0
2011,wagon r,2.85,4.15,5200,Petrol,Dealer,Manual,0
2014,swift,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...
2016,city,9.50,11.60,33988,Diesel,Dealer,Manual,0
2015,brio,4.00,5.90,60000,Petrol,Dealer,Manual,0
2009,city,3.35,11.00,87934,Petrol,Dealer,Manual,0
2017,city,11.50,12.50,9000,Diesel,Dealer,Manual,0
2016,brio,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [ ]:
# Filling missing value with fillna         ( Series + DataFrame )

df['Owner'].fillna('Unknown')

Year
2014    0
2013    0
2017    0
2011    0
2014    0
       ..
2016    0
2015    0
2009    0
2017    0
2016    0
Name: Owner, Length: 301, dtype: int64

In [ ]:
df

,Name,Selling_Price,Present_Price,Kms,Fuel_Type,Seller_Type,Transmission,Owner
Year,,,,,,,,
2014,ritz,3.35,5.59,27000,Petrol,Dealer,Manual,0
2013,sx4,4.75,9.54,43000,Diesel,Dealer,Manual,0
2017,ciaz,7.25,9.85,6900,Petrol,Dealer,Manual,0
2011,wagon r,2.85,4.15,5200,Petrol,Dealer,Manual,0
2014,swift,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...
2016,city,9.50,11.60,33988,Diesel,Dealer,Manual,0
2015,brio,4.00,5.90,60000,Petrol,Dealer,Manual,0
2009,city,3.35,11.00,87934,Petrol,Dealer,Manual,0
2017,city,11.50,12.50,9000,Diesel,Dealer,Manual,0
2016,brio,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [ ]:
df.fillna(0)

,Name,Selling_Price,Present_Price,Kms,Fuel_Type,Seller_Type,Transmission,Owner
Year,,,,,,,,
2014,ritz,3.35,5.59,27000,Petrol,Dealer,Manual,0
2013,sx4,4.75,9.54,43000,Diesel,Dealer,Manual,0
2017,ciaz,7.25,9.85,6900,Petrol,Dealer,Manual,0
2011,wagon r,2.85,4.15,5200,Petrol,Dealer,Manual,0
2014,swift,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...
2016,city,9.50,11.60,33988,Diesel,Dealer,Manual,0
2015,brio,4.00,5.90,60000,Petrol,Dealer,Manual,0
2009,city,3.35,11.00,87934,Petrol,Dealer,Manual,0
2017,city,11.50,12.50,9000,Diesel,Dealer,Manual,0
2016,brio,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [ ]:
df['Name'].fillna(method = 'ffill')

/tmp/ipython-input-1818830353.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Name'].fillna(method = 'ffill')

Year
2014       ritz
2013        sx4
2017       ciaz
2011    wagon r
2014      swift
         ...
2016       city
2015       brio
2009       city
2017       city
2016       brio
Name: Name, Length: 301, dtype: object

In [ ]:
df

,Name,Selling_Price,Present_Price,Kms,Fuel_Type,Seller_Type,Transmission,Owner
Year,,,,,,,,
2014,ritz,3.35,5.59,27000,Petrol,Dealer,Manual,0
2013,sx4,4.75,9.54,43000,Diesel,Dealer,Manual,0
2017,ciaz,7.25,9.85,6900,Petrol,Dealer,Manual,0
2011,wagon r,2.85,4.15,5200,Petrol,Dealer,Manual,0
2014,swift,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...
2016,city,9.50,11.60,33988,Diesel,Dealer,Manual,0
2015,brio,4.00,5.90,60000,Petrol,Dealer,Manual,0
2009,city,3.35,11.00,87934,Petrol,Dealer,Manual,0
2017,city,11.50,12.50,9000,Diesel,Dealer,Manual,0
2016,brio,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [ ]:
# Drop_Duplicate ( Series + DataFrane )   -> to show how much data is duplicate

car = df['Name']

In [ ]:
car.duplicated().sum()

np.int64(203)

In [ ]:
car = car.drop_duplicates()

In [ ]:
car

Year
2014       ritz
2013        sx4
2017       ciaz
2011    wagon r
2014      swift
         ...
2012      verna
2013       city
2015       brio
2014      amaze
2016       jazz
Name: Name, Length: 98, dtype: object

In [ ]:
df.duplicated()

Year
2014    False
2013    False
2017    False
2011    False
2014    False
        ...
2016    False
2015    False
2009    False
2017    False
2016    False
Length: 301, dtype: bool

In [ ]:
df.drop_duplicates()

,Name,Selling_Price,Present_Price,Kms,Fuel_Type,Seller_Type,Transmission,Owner
Year,,,,,,,,
2014,ritz,3.35,5.59,27000,Petrol,Dealer,Manual,0
2013,sx4,4.75,9.54,43000,Diesel,Dealer,Manual,0
2017,ciaz,7.25,9.85,6900,Petrol,Dealer,Manual,0
2011,wagon r,2.85,4.15,5200,Petrol,Dealer,Manual,0
2014,swift,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...
2016,city,9.50,11.60,33988,Diesel,Dealer,Manual,0
2015,brio,4.00,5.90,60000,Petrol,Dealer,Manual,0
2009,city,3.35,11.00,87934,Petrol,Dealer,Manual,0
2017,city,11.50,12.50,9000,Diesel,Dealer,Manual,0
2016,brio,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [ ]:
# drop (Series + DataFrame)

df.drop('Seller_Type',axis=1 , inplace=True)

In [ ]:
df

,Name,Selling_Price,Present_Price,Kms,Fuel_Type,Transmission,Owner
Year,,,,,,,
2014,ritz,3.35,5.59,27000,Petrol,Manual,0
2013,sx4,4.75,9.54,43000,Diesel,Manual,0
2017,ciaz,7.25,9.85,6900,Petrol,Manual,0
2011,wagon r,2.85,4.15,5200,Petrol,Manual,0
2014,swift,4.60,6.87,42450,Diesel,Manual,0
...,...,...,...,...,...,...,...
2016,city,9.50,11.60,33988,Diesel,Manual,0
2015,brio,4.00,5.90,60000,Petrol,Manual,0
2009,city,3.35,11.00,87934,Petrol,Manual,0
2017,city,11.50,12.50,9000,Diesel,Manual,0
2016,brio,5.30,5.90,5464,Petrol,Manual,0

In [ ]:
# drop (Series + DataFrame)

df.drop('Selling_Price',axis=1 , inplace=True)

In [ ]:
df

         Name  Present_Price    Kms Fuel_Type Transmission  Owner
Year
2014     ritz           5.59  27000    Petrol       Manual      0
2013      sx4           9.54  43000    Diesel       Manual      0
2017     ciaz           9.85   6900    Petrol       Manual      0
2011  wagon r           4.15   5200    Petrol       Manual      0
2014    swift           6.87  42450    Diesel       Manual      0
...       ...            ...    ...       ...          ...    ...
2016     city          11.60  33988    Diesel       Manual      0
2015     brio           5.90  60000    Petrol       Manual      0
2009     city          11.00  87934    Petrol       Manual      0
2017     city          12.50   9000    Diesel       Manual      0
2016     brio           5.90   5464    Petrol       Manual      0

[301 rows x 6 columns]

In [ ]:
# Apply (Series + Dataframe )

df['Kms'].apply(lambda x : x/1000)

Year
2014    27.000
2013    43.000
2017     6.900
2011     5.200
2014    42.450
         ...
2016    33.988
2015    60.000
2009    87.934
2017     9.000
2016     5.464
Name: Kms, Length: 301, dtype: float64