In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
from google.colab import files

In [ ]:
upload = files.upload()

Saving Titanic.csv to Titanic.csv

In [ ]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
a*4

array([ 4,  8, 12, 16])

In [ ]:
# Show error because it not deal with None

# s = [ 'cat' , 'mat' , None , 'rat']

# [i.startswith('c') for i in s ]

In [ ]:
# To solve above problem : --

s = [ 'cat' , 'mat' ,  'rat']

# Using a list comprehension:
# result = [i.startswith('c') for i in s]

# Or by converting to a pandas Series:
s_series = pd.Series(s)
result = s_series.str.startswith('c')

print(result)

0     True
1    False
2    False
dtype: bool

In [ ]:
df = pd.read_csv('Titanic.csv')

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [ ]:
# Common function

# lower / upper / captatial / tittle

df['Name'].str.lower()

0                                braund, mr. owen harris
1      cumings, mrs. john bradley (florence briggs th...
2                                 heikkinen, miss. laina
3           futrelle, mrs. jacques heath (lily may peel)
4                               allen, mr. william henry
                             ...
886                                montvila, rev. juozas
887                         graham, miss. margaret edith
888             johnston, miss. catherine helen "carrie"
889                                behr, mr. karl howell
890                                  dooley, mr. patrick
Name: Name, Length: 891, dtype: object

In [ ]:
df['Name'].str.upper()

0                                BRAUND, MR. OWEN HARRIS
1      CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...
2                                 HEIKKINEN, MISS. LAINA
3           FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)
4                               ALLEN, MR. WILLIAM HENRY
                             ...
886                                MONTVILA, REV. JUOZAS
887                         GRAHAM, MISS. MARGARET EDITH
888             JOHNSTON, MISS. CATHERINE HELEN "CARRIE"
889                                BEHR, MR. KARL HOWELL
890                                  DOOLEY, MR. PATRICK
Name: Name, Length: 891, dtype: object

In [ ]:
df['Name'].str.len()

0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Name, Length: 891, dtype: int64

In [ ]:
df['Name'].str.len().max()

82

In [ ]:
df['Name'].str.len() == 82

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Name, Length: 891, dtype: bool

In [ ]:
df['Name'][df['Name'].str.len() == 82].values[0]

'Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)'

In [ ]:
"                      Gopal          ".strip()

'Gopal'

In [ ]:
df['Name'].str.strip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [ ]:
# Split --> get

df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [ ]:
df['lastname'] = df['Name'].str.split(',').str.get(0)

In [ ]:
df['firstname'] =  df['Name'].str.split(',').str.get(1).str.strip().str.split(' ',n=1,expand=True)[1]

In [ ]:
df.sample()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,lastname,firstname
212,213,0,3,"Perkin, Mr. John Henry",male,22.0,0,0,A/5 21174,7.25,NaN,S,Perkin,John Henry

In [ ]:
df['title'] = df['Name'].str.split(',').str.get(1).str.strip().str.split(' ',n=1,expand=True)[0]

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,lastname,firstname,title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Owen Harris,Mr.
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,John Bradley (Florence Briggs Thayer),Mrs.
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Laina,Miss.
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Futrelle,Jacques Heath (Lily May Peel),Mrs.
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Allen,William Henry,Mr.

In [ ]:
df['title'].value_counts()

title
Mr.          517
Miss.        182
Mrs.         125
Master.       40
Dr.            7
Rev.           6
Col.           2
Mlle.          2
Major.         2
Ms.            1
Mme.           1
Don.           1
Lady.          1
Sir.           1
Capt.          1
the            1
Jonkheer.      1
Name: count, dtype: int64

In [ ]:
# Replace

df['title'] =  df['title'].str.replace('Ms.','Miss.')
df['title'] =  df['title'].str.replace('Mlle.','Miss.')

In [ ]:
df['title'].value_counts()

title
Mr.          517
Miss.        185
Mrs.         125
Master.       40
Dr.            7
Rev.           6
Major.         2
Col.           2
Don.           1
Lady.          1
Mme.           1
Sir.           1
Capt.          1
the            1
Jonkheer.      1
Name: count, dtype: int64

In [ ]:
# Startwith / endwith

df['firstname'].str.startswith('A').value_counts()

firstname
False    796
True      95
Name: count, dtype: int64

# Deal with time -> Pandas

In [ ]:
type(pd.Timestamp('2023-01-01'))

pandas._libs.tslibs.timestamps.Timestamp

In [ ]:
# Using text

pd.Timestamp('6th January 2020')

Timestamp('2020-01-06 00:00:00')

In [ ]:
# provide time

pd.Timestamp('6th January 2020 9:21AM')

Timestamp('2020-01-06 09:21:00')

In [ ]:
# provide time

pd.Timestamp('6th January 2020 9:21PM')

Timestamp('2020-01-06 21:21:00')

In [ ]:
# Using python datetime

import datetime as dt

dt.datetime(2023,1,1)

datetime.datetime(2023, 1, 1, 0, 0)

In [ ]:
x = pd.Timestamp(dt.datetime(2023,1,1))

In [ ]:
x.year

2023

In [ ]:
x.month

1

In [ ]:
x.day

1

In [ ]:
x.hour

0

In [ ]:
x.minute

0

In [ ]:
x.second

0

In [ ]:
import numpy as np
date = np.array('2020-01-01',dtype=np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [ ]:
date + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

# DatetimeIndex Object

In [ ]:
pd.DatetimeIndex(['2020-01-01','2020-01-03','2020-01-05'])

DatetimeIndex(['2020-01-01', '2020-01-03', '2020-01-05'], dtype='datetime64[ns]', freq=None)

In [ ]:
# By using python datetime

pd.DatetimeIndex([dt.datetime(2020,1,1),dt.datetime(2020,1,3),dt.datetime(2020,1,5)])

DatetimeIndex(['2020-01-01', '2020-01-03', '2020-01-05'], dtype='datetime64[ns]', freq=None)

# Date Range function

In [ ]:
pd.date_range('2020-01-01',periods=10)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
pd.date_range(start = '2020-02-02' , end = '2020-03-02' , freq = '12H')

/tmp/ipython-input-3163830265.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  pd.date_range(start = '2020-02-02' , end = '2020-03-02' , freq = '12H')

DatetimeIndex(['2020-02-02 00:00:00', '2020-02-02 12:00:00',
               '2020-02-03 00:00:00', '2020-02-03 12:00:00',
               '2020-02-04 00:00:00', '2020-02-04 12:00:00',
               '2020-02-05 00:00:00', '2020-02-05 12:00:00',
               '2020-02-06 00:00:00', '2020-02-06 12:00:00',
               '2020-02-07 00:00:00', '2020-02-07 12:00:00',
               '2020-02-08 00:00:00', '2020-02-08 12:00:00',
               '2020-02-09 00:00:00', '2020-02-09 12:00:00',
               '2020-02-10 00:00:00', '2020-02-10 12:00:00',
               '2020-02-11 00:00:00', '2020-02-11 12:00:00',
               '2020-02-12 00:00:00', '2020-02-12 12:00:00',
               '2020-02-13 00:00:00', '2020-02-13 12:00:00',
               '2020-02-14 00:00:00', '2020-02-14 12:00:00',
               '2020-02-15 00:00:00', '2020-02-15 12:00:00',
               '2020-02-16 00:00:00', '2020-02-16 12:00:00',
               '2020-02-17 00:00:00', '2020-02-17 12:00:00',
               '2020-02-18 00:00:00', '2020-02-18 12:00:00',
               '2020-02-19 00:00:00', '2020-02-19 12:00:00',
               '2020-02-20 00:00:00', '2020-02-20 12:00:00',
               '2020-02-21 00:00:00', '2020-02-21 12:00:00',
               '2020-02-22 00:00:00', '2020-02-22 12:00:00',
               '2020-02-23 00:00:00', '2020-02-23 12:00:00',
               '2020-02-24 00:00:00', '2020-02-24 12:00:00',
               '2020-02-25 00:00:00', '2020-02-25 12:00:00',
               '2020-02-26 00:00:00', '2020-02-26 12:00:00',
               '2020-02-27 00:00:00', '2020-02-27 12:00:00',
               '2020-02-28 00:00:00', '2020-02-28 12:00:00',
               '2020-02-29 00:00:00', '2020-02-29 12:00:00',
               '2020-03-01 00:00:00', '2020-03-01 12:00:00',
               '2020-03-02 00:00:00'],
              dtype='datetime64[ns]', freq='12h')

In [ ]:
# Year end

pd.date_range(start = '2020-02-02' , end = '2025-03-02' , freq = 'A')

/tmp/ipython-input-4111519599.py:3: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  pd.date_range(start = '2020-02-02' , end = '2025-03-02' , freq = 'A')

DatetimeIndex(['2020-12-31', '2021-12-31', '2022-12-31', '2023-12-31',
               '2024-12-31'],
              dtype='datetime64[ns]', freq='YE-DEC')

#  to_datetime function